name: Create Release And Upload Binary To Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Build
        run: make all

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release-${{ matrix.os }}
          path: build/*.tgz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: build/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}